{% set version = '0.1-11' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-predicts
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/predicts_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/predicts/predicts_{{ version }}.tar.gz
  sha256: 39de4c59191fa3df8c6eedddbcd32f240d99cd1224a38a30a222727cbc576acb

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip                # [win]
    - msys2-conda-epoch ==20160418  # [win]
    - cross-r-base {{ r_base }}     # [build_platform != target_platform]
  host:
    - r-base
    - r-terra
  run:
    - r-base
    - r-terra

test:
  commands:
    - $R -e "library('predicts')"           # [not win]
    - "\"%R%\" -e \"library('predicts')\""  # [win]

about:
  home: https://rspatial.org/sdm/
  license: GPL-3.0-or-later
  summary: Methods for spatial predictive modeling, especially for spatial distribution models.
    This includes algorithms for model fitting and prediction, as well as methods for
    model evaluation.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - Rassine

# Package: predicts
# Type: Package
# Title: Spatial Prediction Tools
# Description: Methods for spatial predictive modeling, especially for spatial distribution models. This includes algorithms for model fitting and prediction, as well as methods for model evaluation.
# Version: 0.1-11
# Date: 2023-10-12
# Depends: R (>= 3.5.0), methods, terra
# Suggests: disdat, rJava
# Authors@R: c( person("Robert J.", "Hijmans", role = c("cre", "aut"), email = "r.hijmans@gmail.com", comment = c(ORCID = "0000-0001-5872-2872")), person("Steven", "Phillips", role = "ctb"), person("Chris", "Brunsdon", role = "ctb"), person("Barry", "Rowlingson", role = "ctb"))
# Maintainer: Robert J. Hijmans <r.hijmans@gmail.com>
# License: GPL (>= 3)
# LazyLoad: yes
# URL: https://rspatial.org/sdm/
# BugReports: https://github.com/rspatial/predicts/issues/
# NeedsCompilation: no
# Packaged: 2023-10-12 15:07:42 UTC; rhijm
# Author: Robert J. Hijmans [cre, aut] (<https://orcid.org/0000-0001-5872-2872>), Steven Phillips [ctb], Chris Brunsdon [ctb], Barry Rowlingson [ctb]
# Repository: CRAN
# Date/Publication: 2023-10-12 15:40:02 UTC
